# Generated by Django 3.1.2 on 2021-11-29 17:15

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_auto_20211129_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='name'),
        ),
    ]
